# Generated by Django 3.0.8 on 2020-07-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_date',
            new_name='create_data',
        ),
    ]
